[project]
name = "barflow-manager"
version = "0.1.0"
description = "BarFlow - Gestione Finanziaria per Bar"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "lxml>=4.9.0",
    "openpyxl>=3.1.0",
    "pandas>=2.0.0",
    "plotly>=5.15.0",
    "pyinstaller>=5.13.0",
    "pyside6>=6.5.0",
    "xlsxwriter>=3.1.0",
    "matplotlib>=3.7.0",
    "seaborn>=0.13.2",
]

[tool.uv]
package = true
